export const WEBHOOK_DELIVERY_TIMEOUT_MS = 5_000;
export const WEBHOOK_MAX_ATTEMPTS = 8;
export const WEBHOOK_PROCESS_BATCH_SIZE = 20;
export const WEBHOOK_PROCESS_INTERVAL_MS = 15_000;
export const WEBHOOK_BACKOFF_BASE_MS = 30_000;
export const WEBHOOK_BACKOFF_MAX_MS = 3_600_000;
